### ISSUE TITLE
运行正常，一直提示检测不到人脸，后台报错

### ISSUE THREAD

**Issue by longmingfeng** [itboyst/ArcSoftFaceDemo#11]
![image](https://user-images.githubusercontent.com/26614867/81466933-dbe70c00-9207-11ea-96ce-94eb5b9451ef.png)

**Comment by longmingfeng** [comment]
020-05-09 15:02:52.520 ERROR 12280 --- [nio-8089-exec-8] c.i.f.s.impl.FaceEngineServiceImpl       : 

java.lang.NullPointerException: null
	at com.arcsoft.face.FaceEngine.detectFaces(FaceEngine.java:341) ~[arcsoft-sdk-face-2.2.0.1.jar:na]
	at com.itboyst.facedemo.service.impl.FaceEngineServiceImpl.extractFaceFeature(FaceEngineServiceImpl.java:176) ~[classes/:na]
	at com.itboyst.facedemo.controller.FaceController.faceAdd(FaceController.java:74) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_40]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_40]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_40]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_40]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) [spring-web-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) [spring-web-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106) [spring-webmvc-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879) [spring-webmvc-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.

**Comment by longmingfeng** [comment]
将lib包换成arcsoft-sdk-face-3.0.0.0.jar，pom文件中也换成对应arcsoft-sdk-face-3.0.0.0.jar，就可以了
